import sqlite3
import os

# 楽曲データベースのパス
DB_PATH = "songs.db"

# 手動修正が必要なアーティストのリスト (186件)
MANUAL_READINGS = {
    "ずっと真夜中でいいのに。": "ずっとまよなかでいいのに",
    "indigo la End": "いんでぃごらえんど",
    "EGOIST": "えごいすと",
    "ET-KING": "いーてぃーきんぐ",
    "Absolute area": "あぶそりゅーとえりあ",
    "androp": "あんどろっぷ",
    "＝LOVE": "いこーるらぶ",
    "神様、僕は気づいてしまった": "かみさまぼくはきづいてしまった",
    "ゲスの極み乙女。": "げすのきわみおとめ",
    "Galileo Galilei": "がりれおがりれい",
    "CUTIE STREET": "きゅーてぃーすとりーと",
    "クリス・ハート": "くりすはーと",
    "CANDY TUNE": "きゃんでぃちゅーん",
    "SPiCYSOL": "すぱいしーそる",
    "CK": "しーあんどけー",
    "the shes gone": "ざしーずごーん",
    "DOES": "だず",
    "CHiCO with HoneyWorks": "ちこうぃずはにーわーくす",
    "DEEP": "でぃーぷ",
    "Number_i": "なんばーあい",
    "ハジ→": "はじ",
    "whiteeeen": "ほわいてぃーん",
    "B’z": "びーず",
    "FOMARE": "ふぉまれ",
    "FRUITS ZIPPER": "ふるーつじっぱー",
    "L’Arc~en~Ciel": "らるくあんしえる",
    "redballoon": "れっどばるーん",
    "Rin音": "りんね",
    "reGretGirl": "りぐれっとがーる",
    "りりあ。": "りりあ",
    "adieu[上白石萌歌]": "あでゅー",
    "Mirage Collective": "みらーじゅこれくてぃぶ",
    "Motoki Ohmori[大森元貴]": "おおもりもとき",
    "シュヴァルグラン(CV.夏吉ゆうこ": "しゅばるぐらん",
    "TREASURE": "とれじゃー",
    "L’Arc-en-Ciel": "らるくあんしえる",
    "POSSIBILITY": "ぽっしびりてぃ",
    "Tele": "てれ",
    "Sound Schedule": "さうんどすけじゅーる",
    "千石撫子(花澤香菜": "せんごくなでこ",
    "AiScReam": "あいすくりーむ",
    "Chevon": "しぇぼん",
    "DeNeel": "でにーる",
    "HALVES": "はーぶす",
    "=LOVE": "いこーるらぶ",
    "ZIGGY": "じぎー",
    "Prague": "ぷらーぐ",
    "HUNTR/X": "はんたーはんたー",
    "米津玄師, 宇多田ヒカル": "よねづけんしうただひかる",
    "Wake Up, Girls!": "うぇいくあっぷがーるず",
    "Maverick Mom": "まべりっくまむ",
    "NoisyCell": "のいじーせる",
    "MAKE-UP": "めいくあっぷ",
    "ACE COLLECTION": "えーすこれくしょん",
    "luv": "らぶ",
    "Hi-STANDARD": "はいすたんだーど",
    "never young beach": "ねばーやんぐびーち",
    "≠ME": "のいみー",
    "a flood of circle": "あふらっどおぶさーくる",
    "MAISONdes": "めぞんで",
    "muque": "みゅーく",
    "久保田利伸 with NAOMI CAMPBELL": "くぼたとしのぶうぃずなおみきゃんべる",
    "bokula.": "ぼくら",
    "jo0ji": "じょーじ",
    "神が残した夢を喰う。": "かみがのこしたゆめをくう",
    "GReeeeN[現GRe4N BOYZ]": "ぐりーん",
    "M!LK": "みるく",
    "CHAGE and ASKA": "ちゃげあんどあすか",
    "First Place": "ふぁーすとぷれいす",
    "Conton Candy": "こんとんきゃんでぃ",
    "SHOW-YA": "しょうや",
    "焚吐×みやかわくん": "たくとみやかわくん",
    "BLANKEY JET CITY": "ぶらんきーじぇっとしてぃ",
    "the pillows": "ざぴろうず",
    "Wurts": "わーつ",
    "Avril Lavigne": "あぶりるらびーん",
    "Ray": "れい",
    "LOOK": "るっく",
    "ViViD": "びびっど",
    "BAD HOP": "ばっどほっぷ",
    "serial TV drama": "しりあるてれびどらま",
    "H2O": "えいちつーおー",
    "中山美穂＆WANDS": "なかやまみほうぃずわんず",
    "BRAHMAN": "ぶらふまん",
    "syudou": "しゅどう",
    "BAND-MAID": "ばんどめいど",
    "millennium parade × 椎名林檎": "みれにあむぱれーどしいなりんご",
    "音羽-otoha-": "おとは",
    "milet×MAN WITH A MISSION": "みれいまんうぃずあみっしょん",
    "Liyuu": "りーゆう",
    "SINGER SONGER": "しんがーそんがー",
    "chelmico": "ちぇるみこ",
    "JO1": "じぇーおーわん",
    "go!go!vanillas": "ごーごーばにらず",
    "the peggies": "ざぺぎーず",
    "Mr.FanTastiC": "みすたーふぁんたすてぃっく",
    "day after tomorrow": "でいあふたーとぅもろー",
    "Mr.ふぉるて": "みすたーふぉるて",
    "BREAKERZ": "ぶれいかーず",
    "スピラ・スピカ": "すぴらすぴか",
    "Hump Back": "はんぷばっく",
    "HIKAKIN & SEIKIN": "ひかきんあんどせいきん",
    "FantasticYouth": "ふぁんたすてぃっくゆーす",
    "THE BEAT GARDEN": "ざびーとがーでん",
    "OxT": "おくとい",
    "KOH+": "こーぷらす",
    "THE ROOTLESS": "ざるーとれす",
    "PEOPLE 1": "ぴーぷるわん",
    "Nozomi Kitay & GAL D": "きたやのぞみあんどぎゃるでぃー",
    "ARuFa": "あるふぁ",
    "THE SUPER FRUIT": "ざすーぱーふるーつ",
    "MY FIRST STORY × HYDE": "まいふぁーすとすとーりーはいど",
    "Hilcrhyme(ヒルクライム": "ひるくらいむ",
    "GReeeeN [現 GRe4N BOYZ]": "ぐりーん",
    "GALNERYUS": "がるねりうす",
    "ランカ・リー＝中島愛": "らんかりーなかじまめぐみ",
    "音虎とErii": "ねとらとえりい",
    "GEMN": "じぇむ",
    "mihimaru GT": "みひまるじーてぃー",
    "BACK-ON×FLOW": "ばっくおんふろう",
    "back numberと秦 基博と小林武史": "ばっくなんばーはたもとひろこばやしたけし",
    "Janne Da Arc": "じゃんぬだあるく",
    "GARNET CROW": "がーねっとくろう",
    "PENGUIN RESEARCH": "ぺんぎんりさーち",
    "andymori": "あんでぃもり",
    "Rhythmic Toy World": "りずみっくといわーるど",
    "halyosy": "はりーおしー",
    "BURNOUT SYNDROMES": "ばーんあうとしんどろーむ",
    "SICK HACK": "しっくはっく",
    "Chilli Beans.": "ちりびーんず",
    "Syrup 16g": "しろっぷじゅうろくぐらむ",
    "After the Rain": "あふたーざれい",
    "Bialystocks": "びありすとっくす",
    "The Weeknd": "ざうぃーけんど",
    "Siip": "しーぷ",
    "PK shampoo": "ぴーけーしゃんぷー",
    "H Jungle with t": "えいちじゃんぐるうぃずてぃー",
    "This is LAST": "でぃすいずらすと",
    "Kroi": "くろい",
    "Non Stop Rabbit": "のんすとっぷらびっと",
    "LONGMAN": "ろんぐまん",
    "SIX LOUNGE": "しっくすらうんじ",
    "ASKA": "あすか",
    "w.o.d.": "だぶりゅーおーでぃー",
    "PENICILLIN": "ぺにしりん",
    "BAAD": "ばーど",
    "Harry Styles": "はりーすたいるず",
    "THEE MICHELLE GUN ELEPHANT": "ぜみっしぇるがんえれふぁんと",
    "SURFACE": "さーふぇす",
    "AliA": "ありあ",
    "DaizyStripper": "でいじーすとりっぱー",
    "Foorin": "ふーりん",
    "Lia": "りあ",
    "halca": "はるか",
    "cinema staff": "しねますたっふ",
    "Sentimental boys": "せんてぃめんたるぼーいず",
    "AKINO from bless4": "あきのふろむぶれすふぉー",
    "SIAM SHADE": "しゃむしぇいど",
    "TERRASPEX": "てらすぺっくす",
    "LEGO BIG MORL": "れごびっぐもーる",
    "The Songbards": "ざそんぐばーず",
    "the brilliant green": "ざぶりりあんとぐりーん",
    "SEVENTHLINKS feat. flower": "せぶんすりんくすふぃーちゃりんぐふらわー",
    "Who-ya Extended": "ふーやえくすてんでっど",
    "XIIX": "てんてぃー",
    "YEN TOWN BAND": "いぇんたうんばんど",
    "SOLIDEMO": "そりでぃーも",
    "GRANRODEO": "ぐらんろでお",
    "COLOR CREATION": "からーくりえーしょん",
    "The GazettE": "ざがぜっと",
    "GLIM SPANKY": "ぐりむすぱんきー",
    "MUCC": "むっく",
    "THE SIXTH LIE": "ざしっくすらい",
    "TAK MATSUMOTO featuring ZARD": "まつもとたかひろふぃーちゃりんぐざーど",
    "PANDORA feat.Beverly": "ぱんどらふぃーちゃりんぐびばりー",
    "vivid undress": "びびっどあんどれす",
    "TRUSTRICK": "とらすとりっく",
    "ASCA": "あすか",
    "THREE LIGHTS DOWN KINGS": "さんらいつだうんきんぐす",
    "WEAVER": "うぃーばー",
    "FINLANDS": "ふぃんらんず",
    "mol-74": "もるななじゅうよん",
    "SILENT SIREN": "さいれんとさいれん",
    "TAK MATSUMOTO": "まつもとたかひろ",
    "164 feat.GUMI": "いちろくよんふぃーちゃりんぐぐみ",
    "ALI": "あり",
}

def update_manual_readings():
    if not os.path.exists(DB_PATH):
        print(f"❌ データベースファイルが見つかりません: {DB_PATH}")
        return

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    print(f"🔄 {len(MANUAL_READINGS)} 件のアーティスト読みがなを修正します...")

    updated_count = 0
    not_found_count = 0

    for name, reading in MANUAL_READINGS.items():
        # アーティスト名で検索して読みがなを更新
        cursor.execute("UPDATE artists SET reading = ? WHERE name = ?", (reading, name))
        
        if cursor.rowcount > 0:
            updated_count += 1
        else:
            # データベースにその名前が存在しない場合
            not_found_count += 1

    conn.commit()
    conn.close()

    print(f"✅ 更新完了: {updated_count} 件")
    if not_found_count > 0:
        print(f"⚠️ 注意: {not_found_count} 件のアーティストがDBに見つかりませんでした（名前の完全一致が必要です）")

if __name__ == "__main__":
    update_manual_readings()