/** アーティスト名の略称・カタカナ読みから正式名称へのマッピング */
export const SEARCH_ALIASES: Record<string, string> = {
  // === 超定番・現代ポップス・ロック ===
  "ミセス": "Mrs. GREEN APPLE",
  "みせす": "Mrs. GREEN APPLE",
  "ヒゲダン": "Official髭男dism",
  "ひげだん": "Official髭男dism",
  "ワンオク": "ONE OK ROCK",
  "わんおく": "ONE OK ROCK",
  "バウンディ": "Vaundy",
  "ばうんでぃ": "Vaundy",
  "キングヌー": "King Gnu",
  "きんぐぬー": "King Gnu",
  "ヌー": "King Gnu",
  "ヨアソビ": "YOASOBI",
  "よあそび": "YOASOBI",
  "セカオワ": "SEKAI NO OWARI",
  "せかおわ": "SEKAI NO OWARI",
  "ラッド": "RADWIMPS",
  "らっど": "RADWIMPS",
  "ヨルシカ": "ヨルシカ",
  "ずとまよ": "ずっと真夜中でいいのに。",
  "ズトマヨ": "ずっと真夜中でいいのに。",
  "マカエン": "マカロニえんぴつ",
  "まかえん": "マカロニえんぴつ",
  "サウシー": "Saucy Dog",
  "さうしー": "Saucy Dog",
  "リョクシャカ": "緑黄色社会",
  "りょくしゃか": "緑黄色社会",
  "マイヘア": "My Hair is Bad",
  "まいへあ": "My Hair is Bad",
  "ノベブラ": "Novelbright",
  "ノーベル": "Novelbright",
  "ビーファ": "BE:FIRST",
  "びーふぁ": "BE:FIRST",

  // === 英語名のカタカナ読み ===
  "アド": "Ado",
  "あど": "Ado",
  "ユーリ": "優里",
  "ゆうり": "優里",
  "エメ": "Aimer",
  "えめ": "Aimer",
  "ユーアールユー": "Uru",
  "ウル": "Uru",
  "ミレイ": "milet",
  "みれい": "milet",
  "イヴ": "Eve",
  "いゔ": "Eve",
  "いぶ": "Eve",
  "オーサム": "Awesome City Club",
  "ディッシュ": "DISH//",
  "でぃっしゅ": "DISH//",
  "バックナンバー": "back number",
  "ばっくなんばー": "back number",

  // === レジェンド・定番バンド ===
  "ミスチル": "Mr.Children",
  "みすちる": "Mr.Children",
  "ポルノ": "ポルノグラフィティ",
  "ぽるの": "ポルノグラフィティ",
  "バンプ": "BUMP OF CHICKEN",
  "ばんぷ": "BUMP OF CHICKEN",
  "アジカン": "ASIAN KUNG-FU GENERATION",
  "あじかん": "ASIAN KUNG-FU GENERATION",
  "エルレ": "ELLEGARDEN",
  "えるれ": "ELLEGARDEN",
  "ウーバー": "UVERworld",
  "うーばー": "UVERworld",
  "ラルク": "L'Arc~en~Ciel",
  "らるく": "L'Arc~en~Ciel",
  "ブルハ": "THE BLUE HEARTS",
  "ぶるは": "THE BLUE HEARTS",
  "モンパチ": "MONGOL800",
  "もんぱち": "MONGOL800",
  "ドロス": "![Alexandros]",
  "アレキ": "![Alexandros]",
  "カナブーン": "KANA-BOON",
  "かなぶーん": "KANA-BOON",
  "ホルモン": "マキシマム ザ ホルモン",
  "マンウィズ": "MAN WITH A MISSION",
  "テンフィ": "10-FEET",
  "てんふぃ": "10-FEET",
  "スピッツ": "スピッツ",
  "spitz": "スピッツ",

  // === グループ・アイドル・その他 ===
  "ドリカム": "DREAMS COME TRUE",
  "どりかむ": "DREAMS COME TRUE",
  "いきもの": "いきものがかり",
  "エグザイル": "EXILE",
  "えぐざいる": "EXILE",
  "三代目": "三代目 J SOUL BROTHERS from EXILE TRIBE",
  "ジェネ": "GENERATIONS from EXILE TRIBE",
  "ストーンズ": "SixTONES",
  "すとーんず": "SixTONES",
  "スノ": "Snow Man",
  "すの": "Snow Man",
  "エイト": "関ジャニ∞",
  "キンキ": "KinKi Kids",
  "ももクロ": "ももいろクローバーZ",
  "モー娘。": "モーニング娘。",
  "ニジュー": "NiziU",
  "にじゅー": "NiziU",
  "パフューム": "Perfume",
  "ぱふゅーむ": "Perfume",
  "ビッシュ": "BiSH",
  "びっしゅ": "BiSH",

  // === よくある略称（ソロアーティスト等） ===
  "ユーミン": "松任谷由実",
  "ゆーみん": "松任谷由実",
  "林檎": "椎名林檎",
  "りんご": "椎名林檎",
  "事変": "東京事変",
  "じへん": "東京事変",
  "源さん": "星野源",
  "げんさん": "星野源",
};
